### PR TITLE
Adding files for the cloud functions.

### LINKED ISSUE #61: Create cloud function to save county CSV to bucket
- [ ] Deploy cloud function on GCS and test on incoming data.

### PR DESCRIPTION
**Pull request by efawe**
Fixes #61 

Proxy to what is currently being run on the gcp

### CODE REVIEW

**Comment by isaacmg** [comment]
So I looked over the data being persisted on GCS as per #61 it appears that a large amount of counties appearing.

**Comment by isaacmg** [comment]
For instance there is only one county from Italy despite the fact I know there are more data points 
image



there no counties from Massachusetts and only Maine county is Franklin 
image

**Comment by efawe** [comment]
It might have to be from the fact that the min datapoints needed is 60. as the function this was based off of was default set to 60.

**Comment by isaacmg** [comment]
No I couple of those counties I've tested I know have at least 100 data points. There seems to be some other issue.

**Comment by efawe** [comment]
It was the default timeout. It was set to 60 seconds which is way too low for everything it needs to do. Also corrected some code.

**Comment by efawe** [comment]
So running into a timeout issue. The max time for a function to run is 540 seconds or 9 minutes but the function still needs more time to complete all of it. It gets to around 36% before timing out.

**Comment by isaacmg** [comment]
Maybe try increasing the RAM? I also put out a call to the team. There might be a faster way to handle this than looping through everything.

**Pull request closed without merging**
