### PR TITLE
Solar data trained and added

### PR DESCRIPTION
**Pull request by Pranjalya**

### CODE REVIEW

**Comment by Pranjalya** [comment]
Okay... I'm running the sweeps for solar data again, while dropping the other columns, reducing it to 3 dimensions.
As for wind data, what do you suggest we do? For all the countries it'd take too much time. I suggest, currently, we run it for 4-5 countries data, so we can generate the report, for those countries. What do you suggest?

**Comment by isaacmg** [comment]
Yeah just do it on a few countries for now and not only all of them. Also it would be good if you passed in the weights of the previous run so became one big pre-trained model. I'll DM you code.

**Comment by Pranjalya** [comment]
I've updated the solar code. You can check out the weights in wandb, link is given inside the notebook. Will update wind soon.

**Comment by Pranjalya** [comment]
Updated the wind code. The sweeps are in the link, and the pretrained models for the specified countries. I still have the models for individual country though. There was some encoding error with the added weights, which I tried to resolve, but it was taking some time. So, I've noted the issue for another time.

**Pull request merged**
